//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace comeconv.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffmpeg.exe")]
        public string ExecFile {
            get {
                return ((string)(this["ExecFile"]));
            }
            set {
                this["ExecFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExecCommand {
            get {
                return ((string)(this["ExecCommand"]));
            }
            set {
                this["ExecCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BreakCommand {
            get {
                return ((string)(this["BreakCommand"]));
            }
            set {
                this["BreakCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSacEmoji {
            get {
                return ((bool)(this["IsSacEmoji"]));
            }
            set {
                this["IsSacEmoji"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("space")]
        public string SacEmojiMode {
            get {
                return ((string)(this["SacEmojiMode"]));
            }
            set {
                this["SacEmojiMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSacPremium {
            get {
                return ((bool)(this["IsSacPremium"]));
            }
            set {
                this["IsSacPremium"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("henkan")]
        public string SacPremiumMode {
            get {
                return ((string)(this["SacPremiumMode"]));
            }
            set {
                this["SacPremiumMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSacCommLen {
            get {
                return ((bool)(this["IsSacCommLen"]));
            }
            set {
                this["IsSacCommLen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int SacCommLen {
            get {
                return ((int)(this["SacCommLen"]));
            }
            set {
                this["SacCommLen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSacVpos {
            get {
                return ((bool)(this["IsSacVpos"]));
            }
            set {
                this["IsSacVpos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long SacVpos {
            get {
                return ((long)(this["SacVpos"]));
            }
            set {
                this["SacVpos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSacGift {
            get {
                return ((bool)(this["IsSacGift"]));
            }
            set {
                this["IsSacGift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSacEmotion {
            get {
                return ((bool)(this["IsSacEmotion"]));
            }
            set {
                this["IsSacEmotion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSacNicoAd {
            get {
                return ((bool)(this["IsSacNicoAd"]));
            }
            set {
                this["IsSacNicoAd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SacNGLists.txt")]
        public string SacNGLists {
            get {
                return ((string)(this["SacNGLists"]));
            }
            set {
                this["SacNGLists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mp4")]
        public string SacVideoMode {
            get {
                return ((string)(this["SacVideoMode"]));
            }
            set {
                this["SacVideoMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mp4\t-c copy -y \"%OUTFILE%\";flv\t-c copy -y \"%OUTFILE%\";mp4(再エンコード)\t-c:v copy -c:a " +
            "aac -bsf:a aac_adtstoasc -y \"%OUTFILE%\";flv(再エンコード)\t-c:v copy -c:a aac -bsf:a aa" +
            "c_adtstoasc -y \"%OUTFILE%\"")]
        public string SacVideoList {
            get {
                return ((string)(this["SacVideoList"]));
            }
            set {
                this["SacVideoList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsLogging {
            get {
                return ((bool)(this["IsLogging"]));
            }
            set {
                this["IsLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTwiEmoji {
            get {
                return ((bool)(this["IsTwiEmoji"]));
            }
            set {
                this["IsTwiEmoji"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tspace")]
        public string TwiEmojiMode {
            get {
                return ((string)(this["TwiEmojiMode"]));
            }
            set {
                this["TwiEmojiMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTwiCommLen {
            get {
                return ((bool)(this["IsTwiCommLen"]));
            }
            set {
                this["IsTwiCommLen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int TwiCommLen {
            get {
                return ((int)(this["TwiCommLen"]));
            }
            set {
                this["TwiCommLen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsTwiVpos {
            get {
                return ((bool)(this["IsTwiVpos"]));
            }
            set {
                this["IsTwiVpos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long TwiVpos {
            get {
                return ((long)(this["TwiVpos"]));
            }
            set {
                this["TwiVpos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSaveData {
            get {
                return ((bool)(this["IsSaveData"]));
            }
            set {
                this["IsSaveData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("saccubus")]
        public string DispTab {
            get {
                return ((string)(this["DispTab"]));
            }
            set {
                this["DispTab"] = value;
            }
        }
    }
}
